resources:
  - name: repogcp_bindu
    type: GitRepo
    configuration:
      gitProvider: bindu_github
      path: bindushree16/automation_for_gcp 
      buildOn:
         commit: false 
      
pipelines:
  - name: automation_gcp_pipeline
    steps:
      - name: gcp_machine
        type: Bash
        configuration: 
          priority: 0
          timeoutSeconds: 50000
          environmentVariables:
            env1: value1
            env2: value2
          integrations:
            - name: gcp_key  
          inputResources:
            - name: repogcp_bindu
          runtime:       
            type: image     #<image/host>
            image:
              custom:
                name: drydock/u16
                tag: master
        execution:
          onExecute:
            - pwd
            - terraform --version
            - ssh-keygen -t rsa -N "" -f ~/.ssh/id_rsa
            - Place=$(pwd)
            - echo path=$Path  
            - pushd ~/.ssh
            - ls -la
            - popd
            - printenv
            - pushd $res_repogcp_bindu_resourcePath
            - replace_envs $PWD/variable.tf        
            - terraform init 
            - echo "$int_gcp_key_jsonKey" > gcp.json
            - ls -la            
            - terraform apply -auto-approve -var-file="$PWD/gcp.json"
            - terraform output ip
            - bindu_ip_address=$(terraform output ip)
            - echo "$bindu_ip_address"
            - add_pipeline_variables bindu_ip_address=$bindu_ip_address
            - add_pipeline_files $PWD/terraform.tfstate jfrog_pipeline
            - add_pipeline_files ~/.ssh/id_rsa jfrog
            - popd 

      - name: gcp_installation
        type: Bash
        configuration:
          timeoutSeconds: 50000
          environmentVariables:
            env1: value1
            env2: value2
          integrations:
            - name: gcp_key 
            - name: ART_keys
            - name: art  
          inputSteps:
            - name: gcp_machine
          inputResources:
            - name: repogcp_bindu   
          runtime:       
            type: image     #<image/host>
            image:
              custom:
                name: drydock/u16
                tag: master
        execution:
          onExecute:
            - printenv
            - restore_pipeline_files jfrog ~/.ssh/id_rsa
            - pushd $res_repogcp_bindu_resourcePath
            - PWD=$(pwd)
            - echo $PWD
            - replace_envs $PWD/pipeline_installer.sh
            - cat $PWD/pipeline_installer.sh
            - echo $bindu_ip_address
            - chmod 777 "$PWD"/pipeline_installer.sh
            - chmod 777 "$PWD"/test.sh
            - chmod 400 ~/.ssh/id_rsa
            - cat ~/.ssh/id_rsa
            - echo $bindu_ip_address
            - which ssh
            - scp -i ~/.ssh/id_rsa $PWD/pipeline_installer.sh test.sh bindu@$bindu_ip_address:~
            - ssh -i ~/.ssh/id_rsa bindu@$bindu_ip_address ls
            - ssh -i ~/.ssh/id_rsa bindu@$bindu_ip_address "sudo ./pipeline_installer.sh"
            - ssh -i ~/.ssh/id_rsa bindu@$bindu_ip_address "sudo ./test.sh"
            
      - name: Destroy_gcp_machine
        type: Bash
        configuration: 
          priority: 0
          timeoutSeconds: 50000
          environmentVariables:
            env1: value1
            env2: value2
          integrations:
            - name: gcp_key
          inputSteps:
            - name: gcp_installation
          inputResources:
            - name: repogcp_bindu
          runtime:       
            type: image     #<image/host>
            image:
              custom:
                name: drydock/u16
                tag: master
        execution:
          onExecute:  
            - pushd $res_repogcp_bindu_resourcePath
            - echo $PWD
            - echo "$int_gcp_key_jsonKey" > gcp.json 
            - cat gcp.json
            - echo "$bindu_ip_address"
            - restore_pipeline_files jfrog ~/.ssh/id_rsa 
            - terraform init
            - restore_pipeline_files jfrog_pipeline $PWD/terraform.tfstate
            - cat terraform.tfstate
            - terraform destroy -auto-approve 
            - popd
            
            

